include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test

image: docker:19.03.12
services:
  - name: docker:19.03.12-dind
    alias: docker

variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"

.docker-login: &docker-login
  - apk add --update curl && rm -rf /var/cache/apk/*
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

docker-build:
  stage: build
  before_script:
    - *docker-login
  script:
    - echo "Building docker image..."
    - echo $IMAGE_TAG
    - docker build -t $IMAGE_TAG .
    - echo "Build complete."
    - docker push $IMAGE_TAG
    - echo "Push complete."

sast:
  stage: test

trivy-test-job:
  stage: test
  before_script:
    - *docker-login
    - apk add --update curl && rm -rf /var/cache/apk/*
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest"
      | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
    - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  script:
    - echo "Scanning docker image..."
    - "./trivy image $IMAGE_TAG"
    - echo "No docker image issues found."
