name: CI, with security check using Snyk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        # continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          
  build:
    needs: security
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    env:
      GITHUB_PAGES_REPO: "adafycheng/adafycheng.github.io"
      GITHUB_PAGES_PATH: "github_pages"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Extract Version Number of the Application
        run: |
          APP_VERSION=`cat package.json | jq -r '.version'`
          echo "APP_VERSION: $APP_VERSION"
      - name: Check out from GitHub Pages
        uses: actions/checkout@v3
        with:
          repository: adafycheng/adafycheng.github.io
          path: $GITHUB_PAGES_PATH
          ref: 'main'
      - run: ls -l
      - name: Copy files
        run: cp -rf build/* ./$GITHUB_PAGES_PATH
      - name: setup git config
        run: |
          cd $GITHUB_PAGES_PATH
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ secrets.ACTIONS_GITHUB_EMAIL }}"
          git switch -c "v$APP_VERSION"
          git add .
          git commit -m "New build"
      - name: Push to GitHub Pages
        run: git push origin "v$APP_VERSION"

